holding_server: 'noauth'
lobby_server: 'lobby'
default_group: 'default'
member_group: 'members'
deprecated_method_message: 'The method used to authenticate your login is no longer officially supported by this minecraft server you should contact server staff to get more information on how to fix this.'
debug_mode: false
fail_message: "We failed to find you on our whitelist contact support for more help."
auth_modules:
  yaml:
    file: 'whitelist.yaml'
    uuid_mode: false
  mysql:
    host: localhost
    port: 3306
    username: mcwhitelist
    password: 'password'
    database: whitelist
    table: 'whitelist'
    column: 'username'
    uuid_mode: false
    auth_level: 'depreciated'
  http:
    base_url: 'http://example.com'
    method: 'get'
    other_parameters:
      rest_route: '/minecraft_auth/v1/login/'
    uuid_mode: true